# Generated by Django 2.1.4 on 2018-12-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendDjangoWelcome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='favorite',
        ),
    ]
