# Generated by Django 2.1.4 on 2018-12-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendDjangoWelcome', '0003_author_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='_author_favorite_+', to='backendDjangoWelcome.Recipe'),
        ),
    ]
